export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
export const CART_UPDATE_ITEM = "CART_UPDATE_ITEM"

export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS"
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD"

export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS"
export const CART_CLEAN_ITEMS = "CART_CLEAN_ITEMS"

export const CART_CHECK_ITEMS_REQUEST = "CART_CHECK_ITEMS_REQUEST"
export const CART_CHECK_ITEMS_SUCCESS = "CART_CHECK_ITEMS_SUCCESS"
export const CART_CHECK_ITEMS_FAIL = "CART_CHECK_ITEMS_FAIL"

export const REMOVE_CART_ITEMS_FROM_DB_REQUEST = "REMOVE_CART_ITEMS_FROM_DB_REQUEST"
export const REMOVE_CART_ITEMS_FROM_DB_SUCCESS = "REMOVE_CART_ITEMS_FROM_DB_SUCCESS"
export const REMOVE_CART_ITEMS_FROM_DB_FAIL = "REMOVE_CART_ITEMS_FROM_DB_FAIL"
