export const GET_SHIPPING_REQUEST = "GET_SHIPPING_REQUEST"
export const GET_SHIPPING_SUCCESS = "GET_SHIPPING_SUCCESS"
export const GET_SHIPPING_FAIL = "GET_SHIPPING_FAIL"
export const GET_SHIPPING_RESET = "GET_SHIPPING_RESET"
