export const GET_SHIPPING_LIST_REQUEST = "GET_SHIPPING_LIST_REQUEST"
export const GET_SHIPPING_LIST_SUCCESS = "GET_SHIPPING_LIST_SUCCESS"
export const GET_SHIPPING_LIST_FAIL = "GET_SHIPPING_LIST_FAIL"
export const GET_SHIPPING_LIST_RESET = "GET_SHIPPING_LIST_RESET"

export const GET_SHIPPING_BY_ID_REQUEST = "GET_SHIPPING_BY_ID_REQUEST"
export const GET_SHIPPING_BY_ID_SUCCESS = "GET_SHIPPING_BY_ID_SUCCESS"
export const GET_SHIPPING_BY_ID_FAIL = "GET_SHIPPING_BY_ID_FAIL"
export const GET_SHIPPING_BY_ID_RESET = "GET_SHIPPING_BY_ID_RESET"

export const SHIPPING_CREATE_REQUEST = "SHIPPING_CREATE_REQUEST"
export const SHIPPING_CREATE_SUCCESS = "SHIPPING_CREATE_SUCCESS"
export const SHIPPING_CREATE_FAIL = "SHIPPING_CREATE_FAIL"
export const SHIPPING_CREATE_RESET = "SHIPPING_CREATE_RESET"

export const SHIPPING_UPDATE_REQUEST = "SHIPPING_UPDATE_REQUEST"
export const SHIPPING_UPDATE_SUCCESS = "SHIPPING_UPDATE_SUCCESS"
export const SHIPPING_UPDATE_FAIL = "SHIPPING_UPDATE_FAIL"
export const SHIPPING_UPDATE_RESET = "SHIPPING_UPDATE_RESET"

export const SHIPPING_DELETE_REQUEST = "SHIPPING_DELETE_REQUEST"
export const SHIPPING_DELETE_SUCCESS = "SHIPPING_DELETE_SUCCESS"
export const SHIPPING_DELETE_FAIL = "SHIPPING_DELETE_FAIL"
export const SHIPPING_DELETE_RESET = "SHIPPING_DELETE_RESET"
